name: Get Evolution API
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull and Save
        run: |
          docker pull evolutionapi/evolution-api:v1.6.1
          docker save evolutionapi/evolution-api:v1.6.1 > evolution_v161.tar
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: evolution-image
          path: evolution_v161.tar
