name: Get Evolution API
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull and Save
        run: |
          docker pull dav74/evolution-api:latest
          docker save dav74/evolution-api:latest > evolution_stable.tar
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: evolution-image
          path: evolution_stable.tar
